# Generated by Django 5.1.7 on 2025-03-29 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_alter_categoria_options_alter_libro_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
